version: "3"
services:
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis:/data
  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres:/var/lib/postgresql/data
  superset:
    image: amancevice/superset
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
      - ../mapbox_api.key:/mapbox_api.key
volumes:
  postgres:
  redis:
